### ISSUE TITLE
PID file found but either no matching

### ISSUE THREAD

**Issue by esmaily** [guywiththecrack/jira-crack#10]
Hi guys when download file  `atlassian-extras-3.4.6.jar` and cp to `/opt/atlassian/jira/atlassian-jira/WEB-INF/lib/` and restart catch this error.

OS: debian 12
Jira  Version : 9.6.0

PID file found but either no matching process was found or the current user does not have permission to stop the process. Stop aborted

logs for  catalina.out:
```
6 more
        Caused by: java.util.zip.ZipException: zip END header not found
                at java.base/java.util.zip.ZipFile$Source.zerror(Unknown Source)
                at java.base/java.util.zip.ZipFile$Source.findEND(Unknown Source)

javax.naming.NamingException: No naming context bound to this class loader
                at org.apache.naming.ContextBindings.getClassLoader(ContextBindings.java:269)

```

**Comment by guywiththecrack** [comment]
sorry for being late - i just updated the repo which fixes your problem - check it out
